spring.application.name=Catalog_Service


#server port number
server.port=7099

#To make Microservice connecting with 8888 port number
# Link config client with config server
spring.config.import=optional:configserver:

