spring.application.name=User-Service

#server port number
server.port=9091

#To make Microservice connecting with 8888 port number
# Link config client with config server
spring.config.import=optional:configserver:

